-- Receiving methods (issue #83; PLAN §17.1-§17.2, §17.6; ADR-0016).
--
-- Generated by `drizzle-kit generate` and renamed only; the SQL is unedited.
--
-- Two choices in here are deliberate and would otherwise read as omissions:
--
--   1. `user_id ... ON DELETE cascade` — unlike `members.user_id`, which is
--      `set null` so a departed user's member slot keeps its ledger history. A
--      receiving method carries no history: nothing references it (no transaction
--      records which method was used, PLAN §17.5), so when the user goes, it goes.
--
--   2. `receiving_method_user_id_position_idx` is a PLAIN index, NOT unique. A
--      unique (user_id, position) would make every reorder a temp-value dance for
--      no benefit — a duplicate position is an ambiguous order, not corrupt data.
--      Reads break the tie on `id`.
--
-- `rail` is plain text and `details` is jsonb with NO check constraint, NO enum and
-- NO foreign key, on purpose: the rail registry in `src/lib/server/payout-rails/`
-- owns the shape of `details` and rejects an unknown rail. Teaching the database
-- either one is what ADR-0016 rejects — adding a country must stay a code change
-- with no migration.

CREATE TABLE "receiving_method" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"rail" text NOT NULL,
	"details" jsonb NOT NULL,
	"position" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "receiving_method" ADD CONSTRAINT "receiving_method_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "receiving_method_user_id_position_idx" ON "receiving_method" USING btree ("user_id","position");