-- Record-later placeholders — CAPTURES (issue #49; PLAN §7.7, §9; ADR-0012).
--
-- Generated by `drizzle-kit generate` and renamed only; the SQL is unedited.
--
-- THE COLUMN LIST IS THE SPEC. There is no payer, beneficiary, split-mode, item or
-- exchange-rate column, and there must never be one: a Capture that can hold
-- structured splits is a second transaction form, with two shapes to keep correct
-- (ADR-0012). `amount_minor` + `currency` are stored UNINTERPRETED — no rate, no
-- conversion, no settlement equivalent — and nothing that computes a balance reads
-- this table.
--
-- Three choices in here would otherwise read as omissions:
--
--   1. `currency` has NO foreign key to `currencies.code`, unlike
--      `transactions.currency`. A group may delete a custom currency once no
--      TRANSACTION references it (ADR-0014); an FK here would let a placeholder the
--      ledger cannot even see block that delete. The write path validates the code
--      against the group's set instead, and a code may afterwards dangle — the same
--      way `audit_log.entity_id` may.
--
--   2. `resolved_transaction_id ... ON DELETE set null`, not cascade. A Capture is
--      never hard-deleted; a (non-v1) hard delete of the transaction leaves the row
--      RESOLVED — `resolved_at` still stands, so it does not silently reappear in
--      the "Not recorded yet" tray — with a dangling link.
--
--   3. `captures_group_id_open_idx` is PARTIAL. The unrecorded count is recomputed
--      on every `/groups` and group-overview load (PLAN §7.7 "Recall"), and the
--      resolved history only grows while the open set is a queue to empty, so the
--      index stays the size of what is actually pending. Both nulls are in the
--      predicate: a discarded Capture was never resolved, so `resolved_at IS NULL`
--      alone would keep counting it.
--
-- Timestamp naming does NOT follow §7.1's reversal here: `captured_for` is the
-- real-world day and `created_at` is the plain, immutable server insert time (PLAN
-- §9 spells the table exactly this way; there is no `occurred_at`).

CREATE TABLE "captures" (
	"id" text PRIMARY KEY NOT NULL,
	"group_id" text NOT NULL,
	"created_by" text NOT NULL,
	"note" text NOT NULL,
	"amount_minor" bigint,
	"currency" text,
	"captured_for" date DEFAULT now() NOT NULL,
	"resolved_transaction_id" text,
	"resolved_at" timestamp,
	"discarded_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "captures" ADD CONSTRAINT "captures_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "captures" ADD CONSTRAINT "captures_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "captures" ADD CONSTRAINT "captures_resolved_transaction_id_transactions_id_fk" FOREIGN KEY ("resolved_transaction_id") REFERENCES "public"."transactions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "captures_group_id_resolved_at_idx" ON "captures" USING btree ("group_id","resolved_at");--> statement-breakpoint
CREATE INDEX "captures_group_id_open_idx" ON "captures" USING btree ("group_id") WHERE ("captures"."resolved_at" is null and "captures"."discarded_at" is null);