-- A record-later note RE-OPENS while its transaction is soft-deleted (issue #91;
-- PLAN §7.7, §9).
--
-- Generated by `drizzle-kit generate` and renamed only; the SQL is unedited.
--
-- WHY TWO INDEXES AND NO COLUMN. 0020's `resolved_transaction_id ... ON DELETE set
-- null` reasoned about a HARD delete. v1's real delete is a SOFT one
-- (`transactions.deleted_at`, with restore), and it touches nothing in `captures` —
-- so a note recorded into a transaction that was then deleted stayed stamped, while
-- the expense it named was in no balance: neither on the ledger nor in the queue.
--
-- The fix is a READ-TIME rule, not a new column and not a cleared stamp ("resolve
-- is a stamp, not a delete" — §7.7; the trail from remembering to recording has to
-- survive, and the audit log keeps every recording of it). "Open" becomes two
-- disjoint arms:
--
--   1. never stamped   — `resolved_at IS NULL AND discarded_at IS NULL`, which is
--      `captures_group_id_open_idx` (0020), unchanged and still the count's index.
--   2. re-opened       — stamped, not discarded, and the transaction it points at
--      is soft-deleted.
--
-- Arm 2 spans a join, and no partial index can. So it gets its own access path,
-- which is what these two build: find a group's soft-deleted transactions (few,
-- hence a PARTIAL index — the ledger's live rows are not in it), then look up the
-- note pointing at each. Driven that way, the arm costs nothing for a group that
-- has deleted nothing; the alternative — one OR'd query — cannot use either partial
-- index and re-reads the group's whole recorded history on every page load.

CREATE INDEX "transactions_group_id_deleted_idx" ON "transactions" USING btree ("group_id") WHERE "transactions"."deleted_at" is not null;--> statement-breakpoint
CREATE INDEX "captures_resolved_transaction_id_idx" ON "captures" USING btree ("resolved_transaction_id") WHERE "captures"."resolved_transaction_id" is not null;
