import {
	pgTable,
	text,
	boolean,
	integer,
	jsonb,
	timestamp,
	index,
	uniqueIndex
} from 'drizzle-orm/pg-core';
import { session, user } from './auth-schema';

// Drizzle tables backing the connector OAuth authorization server (ADR-0010,
// ADR-0018): `@better-auth/mcp`, which is `@better-auth/oauth-provider` preset for
// MCP, plus the `jwt` plugin that signs its access tokens.
//
// WHY THIS IS HAND-AUTHORED IN ITS OWN FILE (not `auth-schema.ts`):
// `auth-schema.ts` is GENERATED by the better-auth CLI and marked do-not-edit.
// The CLI cannot load THIS config: `auth.ts` pulls `$app/server` /
// `$app/environment` (via the `sveltekitCookies` plugin), which the CLI can't
// resolve. That is the same constraint that put `api_key` (`api-key-schema.ts`)
// and `rate_limit` (`rate-limit-schema.ts`) in their own files.
//
// The tables below were produced by the CLI's own drizzle generator
// (`generateDrizzleSchema` from `auth/api`, v1.7.6) run against a stub config
// with the same plugins, then copied here with the project's snake_case index
// names. So types, nullability (`required !== false` ⇒ `notNull()`), defaults,
// uniques, indexes and FK `onDelete`s are the plugin's contract, not guesses.
//
// ADAPTER RESOLUTION — the export KEYS (`jwks`, `oauthClient`, …) MUST match the
// better-auth model names exactly: the drizzle adapter resolves each model via
// `schema[modelName]` (`usePlural` off) and each field via
// `schemaModel[fieldName]`. The property keys are therefore camelCase; SQL
// names are independent and snake_case.
//
// `string[]` fields are native Postgres `text[]` and `json` fields are `jsonb`:
// the drizzle adapter reports `supportsArrays` / `supportsJSON` for `pg`.

// jwks — the `jwt` plugin's signing keys. The private key is encrypted at rest
// with `BETTER_AUTH_SECRET`; a key pair is created on first use.
export const jwks = pgTable('jwks', {
	id: text('id').primaryKey(),
	publicKey: text('public_key').notNull(),
	privateKey: text('private_key').notNull(),
	createdAt: timestamp('created_at').notNull(),
	expiresAt: timestamp('expires_at'),
	alg: text('alg'),
	crv: text('crv')
});

// oauthClient — a registered OAuth client (e.g. the Claude.ai connector, which
// registers itself through dynamic client registration). `clientId` is unique
// because it is the FK target for the token / consent tables.
export const oauthClient = pgTable(
	'oauth_client',
	{
		id: text('id').primaryKey(),
		clientId: text('client_id').notNull().unique(),
		clientSecret: text('client_secret'),
		clientDiscoveryId: text('client_discovery_id'),
		disabled: boolean('disabled').default(false),
		skipConsent: boolean('skip_consent'),
		enableEndSession: boolean('enable_end_session'),
		subjectType: text('subject_type'),
		scopes: text('scopes').array(),
		clientCredentialsScopes: text('client_credentials_scopes').array().default([]),
		userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
		createdAt: timestamp('created_at'),
		updatedAt: timestamp('updated_at'),
		name: text('name'),
		uri: text('uri'),
		icon: text('icon'),
		contacts: text('contacts').array(),
		tos: text('tos'),
		policy: text('policy'),
		softwareId: text('software_id'),
		softwareVersion: text('software_version'),
		softwareStatement: text('software_statement'),
		redirectUris: text('redirect_uris').array().notNull(),
		postLogoutRedirectUris: text('post_logout_redirect_uris').array(),
		backchannelLogoutUri: text('backchannel_logout_uri'),
		backchannelLogoutSessionRequired: boolean('backchannel_logout_session_required'),
		tokenEndpointAuthMethod: text('token_endpoint_auth_method'),
		applicationType: text('application_type'),
		jwks: text('jwks'),
		jwksUri: text('jwks_uri'),
		grantTypes: text('grant_types').array(),
		responseTypes: text('response_types').array(),
		requirePKCE: boolean('require_pkce'),
		dpopBoundAccessTokens: boolean('dpop_bound_access_tokens').default(false),
		referenceId: text('reference_id'),
		metadata: jsonb('metadata')
	},
	(table) => [index('oauth_client_user_id_idx').on(table.userId)]
);

// oauthResource — a protected resource tokens are issued for. The plugin seeds
// the `/mcp` resource from config on startup (`resource` in `auth.ts`).
export const oauthResource = pgTable('oauth_resource', {
	id: text('id').primaryKey(),
	identifier: text('identifier').notNull().unique(),
	name: text('name').notNull(),
	accessTokenTtl: integer('access_token_ttl'),
	refreshTokenTtl: integer('refresh_token_ttl'),
	signingAlgorithm: text('signing_algorithm'),
	signingKeyId: text('signing_key_id'),
	allowedScopes: text('allowed_scopes').array(),
	customClaims: jsonb('custom_claims'),
	dpopBoundAccessTokensRequired: boolean('dpop_bound_access_tokens_required').default(false),
	disabled: boolean('disabled').default(false),
	createdAt: timestamp('created_at'),
	updatedAt: timestamp('updated_at'),
	policyVersion: integer('policy_version').default(1),
	metadata: jsonb('metadata')
});

// oauthClientResource — which clients may request which resources.
export const oauthClientResource = pgTable(
	'oauth_client_resource',
	{
		id: text('id').primaryKey(),
		clientId: text('client_id')
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: 'cascade' }),
		resourceId: text('resource_id')
			.notNull()
			.references(() => oauthResource.identifier, { onDelete: 'cascade' }),
		metadata: jsonb('metadata'),
		createdAt: timestamp('created_at')
	},
	(table) => [
		uniqueIndex('oauth_client_resource_client_id_resource_id_uidx').on(
			table.clientId,
			table.resourceId
		),
		index('oauth_client_resource_client_id_idx').on(table.clientId),
		index('oauth_client_resource_resource_id_idx').on(table.resourceId)
	]
);

// oauthRefreshToken — an opaque refresh token (stored hashed), rotated on use.
export const oauthRefreshToken = pgTable(
	'oauth_refresh_token',
	{
		id: text('id').primaryKey(),
		token: text('token').notNull().unique(),
		clientId: text('client_id')
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: 'cascade' }),
		sessionId: text('session_id').references(() => session.id, { onDelete: 'set null' }),
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		referenceId: text('reference_id'),
		authorizationCodeId: text('authorization_code_id'),
		resources: text('resources').array(),
		requestedUserInfoClaims: text('requested_user_info_claims').array(),
		expiresAt: timestamp('expires_at').notNull(),
		createdAt: timestamp('created_at').notNull(),
		revoked: timestamp('revoked'),
		rotatedAt: timestamp('rotated_at'),
		rotationReplayResponse: text('rotation_replay_response'),
		rotationReplayExpiresAt: timestamp('rotation_replay_expires_at'),
		authTime: timestamp('auth_time'),
		confirmation: jsonb('confirmation'),
		scopes: text('scopes').array().notNull()
	},
	(table) => [
		index('oauth_refresh_token_client_id_idx').on(table.clientId),
		index('oauth_refresh_token_session_id_idx').on(table.sessionId),
		index('oauth_refresh_token_user_id_idx').on(table.userId),
		index('oauth_refresh_token_authorization_code_id_idx').on(table.authorizationCodeId)
	]
);

// oauthAccessToken — OPAQUE access tokens only. Tokens for `/mcp` are JWTs bound
// to the resource and are never stored; this table holds the ones issued without
// a `resource` (only usable at the userinfo endpoint).
export const oauthAccessToken = pgTable(
	'oauth_access_token',
	{
		id: text('id').primaryKey(),
		token: text('token').notNull().unique(),
		clientId: text('client_id')
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: 'cascade' }),
		sessionId: text('session_id').references(() => session.id, { onDelete: 'set null' }),
		userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
		referenceId: text('reference_id'),
		authorizationCodeId: text('authorization_code_id'),
		resources: text('resources').array(),
		requestedUserInfoClaims: text('requested_user_info_claims').array(),
		refreshId: text('refresh_id').references(() => oauthRefreshToken.id, {
			onDelete: 'cascade'
		}),
		expiresAt: timestamp('expires_at').notNull(),
		createdAt: timestamp('created_at').notNull(),
		revoked: timestamp('revoked'),
		confirmation: jsonb('confirmation'),
		scopes: text('scopes').array().notNull()
	},
	(table) => [
		index('oauth_access_token_client_id_idx').on(table.clientId),
		index('oauth_access_token_session_id_idx').on(table.sessionId),
		index('oauth_access_token_user_id_idx').on(table.userId),
		index('oauth_access_token_authorization_code_id_idx').on(table.authorizationCodeId),
		index('oauth_access_token_refresh_id_idx').on(table.refreshId)
	]
);

// oauthConsent — the scopes a user has granted a client. Denials are not stored.
export const oauthConsent = pgTable(
	'oauth_consent',
	{
		id: text('id').primaryKey(),
		clientId: text('client_id')
			.notNull()
			.references(() => oauthClient.clientId, { onDelete: 'cascade' }),
		userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
		referenceId: text('reference_id'),
		resources: text('resources').array(),
		requestedUserInfoClaims: text('requested_user_info_claims').array(),
		scopes: text('scopes').array().notNull(),
		createdAt: timestamp('created_at').notNull(),
		updatedAt: timestamp('updated_at').notNull()
	},
	(table) => [
		index('oauth_consent_client_id_idx').on(table.clientId),
		index('oauth_consent_user_id_idx').on(table.userId)
	]
);

// oauthClientAssertion — single-use `private_key_jwt` assertion ids (replay guard).
export const oauthClientAssertion = pgTable('oauth_client_assertion', {
	id: text('id').primaryKey(),
	expiresAt: timestamp('expires_at').notNull()
});
