import { pgTable, text, boolean, timestamp, index } from 'drizzle-orm/pg-core';
import { user } from './auth-schema';

// Drizzle tables backing better-auth's `mcp` OAuth authorization server
// (ADR-0010, connector OAuth). The `mcp` plugin is a thin wrapper over the
// `oidcProvider` plugin and registers the SAME three plugin-owned tables —
// `oauthApplication`, `oauthAccessToken`, `oauthConsent` — via the shared
// `schema` object exported from `better-auth/dist/plugins/oidc-provider`.
//
// WHY THIS IS HAND-AUTHORED IN ITS OWN FILE (not `auth-schema.ts`):
// `auth-schema.ts` is GENERATED by `@better-auth/cli generate` and marked
// do-not-edit. The CLI cannot generate tables for THIS config: `auth.ts` pulls
// `$app/server` / `$app/environment` (via the `sveltekitCookies` plugin), which
// the CLI can't resolve, so it errors before emitting anything. That is the
// exact same constraint that forced `api_key` (`api-key-schema.ts`) and
// `rate_limit` (`rate-limit-schema.ts`) into their own hand-authored files, so
// these OAuth tables follow that standing pattern.
//
// ADAPTER RESOLUTION — the export KEYS below (`oauthApplication`,
// `oauthAccessToken`, `oauthConsent`) MUST match the better-auth model names
// exactly, because the drizzle adapter resolves each model via
// `schema[modelName]` (`usePlural` off) and each FIELD via
// `schemaModel[fieldName]`. The property keys are therefore camelCase (the
// better-auth field names); the SQL column/table names are independent and use
// the project's snake_case convention (as in the generated `auth-schema.ts`).
// The field shape (types, required→notNull, unique, index, references/onDelete)
// is mirrored EXACTLY from the plugin's own `schema` definition — the same rule
// better-auth's own migration generator applies (`required !== false` ⇒
// `notNull()`), so nothing is guessed.

// oauthApplication — a registered OAuth client (the Claude.ai connector).
// `clientId` is unique because it is the FK target for the token/consent tables.
export const oauthApplication = pgTable(
	'oauth_application',
	{
		id: text('id').primaryKey(),
		name: text('name').notNull(),
		icon: text('icon'),
		// The plugin JSON.stringifies metadata before it reaches the adapter, so this
		// is a plain string column (optional).
		metadata: text('metadata'),
		clientId: text('client_id').notNull().unique(),
		clientSecret: text('client_secret'),
		// Space/newline-separated allowed redirect URLs, stored as a single string.
		redirectUrls: text('redirect_urls').notNull(),
		// Client type: web | native | user-agent-based | public.
		type: text('type').notNull(),
		disabled: boolean('disabled').default(false),
		// Owning user (optional): cascade-deleted with the user. Indexed for lookups.
		userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at').defaultNow().notNull()
	},
	(table) => [index('oauth_application_user_id_idx').on(table.userId)]
);

// oauthAccessToken — an issued access/refresh token pair bound to a client and
// (optionally) a user. Both tokens are unique lookup columns.
export const oauthAccessToken = pgTable(
	'oauth_access_token',
	{
		id: text('id').primaryKey(),
		accessToken: text('access_token').notNull().unique(),
		refreshToken: text('refresh_token').notNull().unique(),
		accessTokenExpiresAt: timestamp('access_token_expires_at').notNull(),
		refreshTokenExpiresAt: timestamp('refresh_token_expires_at').notNull(),
		// FK → oauthApplication.clientId (its unique column), cascade + indexed.
		clientId: text('client_id')
			.notNull()
			.references(() => oauthApplication.clientId, { onDelete: 'cascade' }),
		// Owning user (optional): cascade-deleted with the user. Indexed.
		userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),
		// Space-separated granted scopes, stored as a single string.
		scopes: text('scopes').notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at').defaultNow().notNull()
	},
	(table) => [
		index('oauth_access_token_client_id_idx').on(table.clientId),
		index('oauth_access_token_user_id_idx').on(table.userId)
	]
);

// oauthConsent — records a user's grant (or denial) of scopes to a client.
export const oauthConsent = pgTable(
	'oauth_consent',
	{
		id: text('id').primaryKey(),
		// FK → oauthApplication.clientId, cascade + indexed.
		clientId: text('client_id')
			.notNull()
			.references(() => oauthApplication.clientId, { onDelete: 'cascade' }),
		// Consenting user, cascade + indexed.
		userId: text('user_id')
			.notNull()
			.references(() => user.id, { onDelete: 'cascade' }),
		scopes: text('scopes').notNull(),
		createdAt: timestamp('created_at').defaultNow().notNull(),
		updatedAt: timestamp('updated_at').defaultNow().notNull(),
		consentGiven: boolean('consent_given').notNull()
	},
	(table) => [
		index('oauth_consent_client_id_idx').on(table.clientId),
		index('oauth_consent_user_id_idx').on(table.userId)
	]
);
