import { pgTable, text, integer, bigint } from 'drizzle-orm/pg-core';

// Drizzle table backing better-auth's DATABASE-backed rate limiting (PLAN §12).
//
// When `auth.ts` sets `rateLimit.storage: 'database'`, better-auth persists its
// per-(IP+path) request counters in this table instead of per-instance memory,
// so the limit is shared across serverless instances (production hardening
// follow-up for task 2.11). better-auth resolves its internal `rateLimit` model
// to the Drizzle schema export whose KEY is `rateLimit` (the drizzle adapter does
// `schema['rateLimit']`, with `usePlural` off), so the exported const MUST be
// named `rateLimit`; the SQL table name (`rate_limit`) is independent.
//
// This lives in its OWN file rather than in `auth-schema.ts` because that file is
// generated by `@better-auth/cli generate` and marked do-not-edit — and the CLI
// cannot generate this table for us here (it can't resolve the `$app/server`
// import the `sveltekitCookies` plugin pulls into `auth.ts`). The field shape is
// mirrored exactly from better-auth's own rate-limit table spec
// (`@better-auth/core` `getAuthTables`): `key` string + UNIQUE + required,
// `count` number/int required, `lastRequest` a bigint ms-epoch required. We use
// the same conventions as the generated `auth-schema.ts`: `text('id').primaryKey()`
// and camelCase property keys mapped to snake_case column names.
export const rateLimit = pgTable('rate_limit', {
	id: text('id').primaryKey(),
	// Lookup column: better-auth keys each counter on IP + request path. UNIQUE per
	// better-auth's spec (`key: { type: 'string', unique: true, required: true }`),
	// which also provides the index for the find-by-key reads the limiter performs.
	key: text('key').notNull().unique(),
	// Request count within the current window; incremented via the adapter's
	// `incrementOne({ increment: { count: 1 } })`.
	count: integer('count').notNull(),
	// Millisecond epoch of the last request. better-auth declares this `bigint`
	// (it stores `Date.now()`), and reads it back as a Number, so we use
	// `mode: 'number'` to match the limiter's `{ mode: 'number' }` expectations.
	lastRequest: bigint('last_request', { mode: 'number' }).notNull()
});
