// Drizzle schema entry point.
//
// drizzle-kit loads this module (see `drizzle.config.ts`) and the app's DB
// client passes it to `drizzle(pool, { schema })` for typed queries. Re-export
// table definitions from here as they are introduced.
//
// Tables added so far:
//   - better-auth tables (task 1.8) → re-exported below from `auth-schema.ts`,
//     which is GENERATED by `@better-auth/cli generate` (do NOT hand-edit it):
//     user / session / account / verification / passkey.
//   - rate_limit (task 2.11 hardening) → re-exported from `rate-limit-schema.ts`,
//     hand-authored (the CLI can't generate it for this config) to back
//     better-auth's DATABASE-backed rate limiting. The `rateLimit` export key
//     MUST be present here so both drizzle-kit and the app's
//     `drizzle(pool, { schema })` pick it up — the drizzle adapter resolves the
//     better-auth `rateLimit` model via `schema['rateLimit']`.
//
// Tables still to come in later tasks:
//   - groups / members         → task 3.1
//   - transactions / audit_log → Phase 4+

export * from './auth-schema';
export * from './rate-limit-schema';
