// Drizzle schema entry point.
//
// drizzle-kit loads this module (see `drizzle.config.ts`) and the app's DB
// client passes it to `drizzle(pool, { schema })` for typed queries. Re-export
// table definitions from here as they are introduced.
//
// Tables added so far:
//   - better-auth tables (task 1.8) → re-exported below from `auth-schema.ts`,
//     which is GENERATED by `@better-auth/cli generate` (do NOT hand-edit it):
//     user / session / account / verification / passkey.
//   - rate_limit (task 2.11 hardening) → re-exported from `rate-limit-schema.ts`,
//     hand-authored (the CLI can't generate it for this config) to back
//     better-auth's DATABASE-backed rate limiting. The `rateLimit` export key
//     MUST be present here so both drizzle-kit and the app's
//     `drizzle(pool, { schema })` pick it up — the drizzle adapter resolves the
//     better-auth `rateLimit` model via `schema['rateLimit']`.
//   - groups / members / invites (task 3.1) → re-exported from `groups-schema.ts`,
//     hand-authored domain tables (PLAN §6, §9): groups (+ soft-delete), member
//     slots (+ soft-deactivate, partial-unique one-member-per-user-per-group),
//     and reusable 7-day invite links (+ revoke).
//   - currencies (task 3.2) → re-exported from `currencies-schema.ts`,
//     hand-authored (PLAN §7.5.1): the 29 supported fiat currencies (code PK,
//     name, exponent, symbol). The table DDL + the 29-row idempotent seed live
//     in the migration; the canonical data is `src/lib/money/currencies.ts`.
//
// Tables still to come in later tasks:
//   - transactions / audit_log → Phase 4+

export * from './auth-schema';
export * from './rate-limit-schema';
export * from './groups-schema';
export * from './currencies-schema';
