// Drizzle schema entry point.
//
// drizzle-kit loads this module (see `drizzle.config.ts`) and the app's DB
// client passes it to `drizzle(pool, { schema })` for typed queries. Re-export
// table definitions from here as they are introduced.
//
// Tables added so far:
//   - better-auth tables (task 1.8) → re-exported below from `auth-schema.ts`,
//     which is GENERATED by `@better-auth/cli generate` (do NOT hand-edit it):
//     user / session / account / verification / passkey.
//   - api_key (task #13) → re-exported from `api-key-schema.ts`, hand-authored
//     (the CLI can't generate it for this config, same `$app/server` constraint as
//     `rate_limit`) to back the `@better-auth/api-key` plugin. The export key MUST
//     be `apikey` — the drizzle adapter resolves the plugin's `apikey` model via
//     `schema['apikey']`.
//   - rate_limit (task 2.11 hardening) → re-exported from `rate-limit-schema.ts`,
//     hand-authored (the CLI can't generate it for this config) to back
//     better-auth's DATABASE-backed rate limiting. The `rateLimit` export key
//     MUST be present here so both drizzle-kit and the app's
//     `drizzle(pool, { schema })` pick it up — the drizzle adapter resolves the
//     better-auth `rateLimit` model via `schema['rateLimit']`.
//   - groups / members / invites (task 3.1) → re-exported from `groups-schema.ts`,
//     hand-authored domain tables (PLAN §6, §9): groups (+ soft-delete), member
//     slots (+ soft-deactivate, partial-unique one-member-per-user-per-group),
//     and reusable 7-day invite links (+ revoke).
//   - currencies (task 3.2) → re-exported from `currencies-schema.ts`,
//     hand-authored (PLAN §7.5.1): the 29 supported fiat currencies (code PK,
//     name, exponent, symbol). The table DDL + the 29-row idempotent seed live
//     in the migration; the canonical data is `src/lib/money/currencies.ts`.
//   - categories / transactions / transaction_payers / transaction_shares /
//     transaction_items / transaction_item_shares / transaction_charges
//     (task 4.2) → re-exported from `transactions-schema.ts`, hand-authored
//     ledger tables (PLAN §9, §7.6, §8). SCHEMA-ONLY: money is integer minor
//     units in `bigint` columns, `exchange_rate` is `numeric(18,6)`, and the
//     enum-like columns are `text`. `categories` is created here and SEEDED in
//     task 4.3 (14 fixed rows + a `sort_order` column; canonical data
//     `src/lib/categories.ts`). The `created_at` (real-world, editable) vs `occurred_at`
//     (immutable server insert time) naming is DELIBERATELY reversed (§7.1).
//   - audit_log (task 4.2) → re-exported from `audit-schema.ts`, the append-only
//     audit trail (PLAN §9, §12.1): no updated_at / no soft-delete; `entity_id`
//     is deliberately NOT a FK (may dangle after hard-delete); `metadata` is
//     `jsonb`. The audit-write helper is task 4.6.
//   - idempotency_key (task #20) → re-exported from `idempotency-schema.ts`,
//     hand-authored (PLAN §16.6): the `/api/v1` write idempotency store. Maps
//     (calling api_key id + client `Idempotency-Key` + request fingerprint) → the
//     stored response, pending-first under a UNIQUE `(key_id, idempotency_key)` so
//     concurrent retries race safely; 24h TTL via `expires_at`.
//   - api_key_class_rate_limit (task #21) → re-exported from
//     `api-key-class-rate-limit-schema.ts`, hand-authored (PLAN §16.7): the TIER-2
//     per-key, class-aware `/api/v1` rate-limit counters. Mirrors `rate_limit`'s
//     4-column shape, keyed `${apiKeyId}:${class}` (class ∈ read|write) with two
//     independent counters (read 100/60s, write 20/60s).

export * from './auth-schema';
export * from './api-key-schema';
export * from './rate-limit-schema';
export * from './groups-schema';
export * from './currencies-schema';
export * from './transactions-schema';
export * from './audit-schema';
export * from './idempotency-schema';
export * from './api-key-class-rate-limit-schema';
